# name: s3
# on:
#   push:
#     branches:
#     -  main
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1

#     - name: AWS
#       uses: aws-actions/configure-aws-credentials@v1
#       with: 
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_S3_REGION }}

#     - name: s3 deploy
#       run: aws s3 sync . s3://nisheshs/ --size-only

#     - name: Notify SNS
#       run: |
#         aws sns publish \
#           --topic-arn arn:aws:sns:us-east-1:806395723933:notificationtopic \
#           --message "Deployment to S3 completed. Files have been uploaded to s3://nisheshs/."

name: S3 Deployment

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Configure AWS
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: List files to deploy
      run: find . -type f -not -path "./.git/*" > files-to-upload.txt

    - name: Deploy to S3
      id: deploy
      run: |
        aws s3 sync . s3://nisheshs/ --delete --exclude ".*"
        aws s3 ls s3://nisheshs/ --recursive > s3-files-list.txt

    - name: Prepare SNS message
      id: prepare-sns-message
      run: |
        if [ $? -eq 0 ]; then
          # Deployment succeeded
          UPDATED_FILES=$(cat files-to-upload.txt)
          UPLOADED_FILES=$(aws s3 ls s3://nisheshs/ --recursive --human-readable)
          MESSAGE="Deployment succeeded.\n\nFiles uploaded to s3://nisheshs/:\n$UPLOADED_FILES"
        else
          # Deployment failed
          MESSAGE="Deployment failed. Please check the logs for details."
        fi
        echo -e "$MESSAGE" > sns-message.txt

    - name: Notify SNS
      run: |
        aws sns publish \
          --topic-arn arn:aws:sns:us-east-1:806395723933:notificationtopic \
          --message file://sns-message.txt





    
   
