# name: s3
# on:
#   push:
#     branches:
#     -  main
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1

#     - name: AWS
#       uses: aws-actions/configure-aws-credentials@v1
#       with: 
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: s3 deploy
#       run: aws s3 cp . s3://nisheshtest/ --recursive   

name: s3
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: AWS
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: s3 deploy
      run: aws s3 cp . s3://nisheshtest/ --recursive

    - name: Notify SNS
      run: |
        aws sns publish \
          --topic-arn arn:aws:sns:us-east-1:806395723933:notificationtopic:fcb98b3b-196d-435f-b728-97b99ed8351 \
          --message "Deployment to S3 completed. Files have been uploaded to s3://nisheshtest/."
      # env:
      #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #   AWS_REGION: us-east-1
