# name: s3
# on:
#   push:
#     branches:
#     -  main
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1

#     - name: AWS
#       uses: aws-actions/configure-aws-credentials@v1
#       with: 
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: s3 deploy
#       run: aws s3 sync . s3://nisheshtest/ --delete --exact-timestamps
      

name: s3
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: AWS
      uses: aws-actions/configure-aws-credentials@v1
      with: 
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Get changed files
      id: get-changed-files
      run: |
        # Get the list of changed files in the last commit
        git diff-tree --no-commit-id --name-only -r HEAD > changed-files.txt
        # Output the list of changed files
        echo "Changed files:"
        cat changed-files.txt

    - name: Upload changed files to S3
      run: |
        # Check if the file list is empty
        if [ -s changed-files.txt ]; then
          echo "Uploading changed files to S3..."
          while IFS= read -r file; do
            if [ -f "$file" ]; then
              echo "Uploading $file to s3://nisheshtest/$file"
              aws s3 sync "$file" s3://nisheshtest/"$file" --delete 
            else
              echo "$file does not exist, skipping."
            fi
          done < changed-files.txt
        else
          echo "No changed files to upload."
        fi
